---
editor_options:
  markdown:
    wrap: 72
output:
  html_document:
    df_print: paged
---

x--- title: "Clusturing ANN" output: html_document: default word_document: default
date: "2023-11-28" ---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r message=FALSE, warning=FALSE}
# Load packages for data manipulation
library(tidyverse)
library(arules)
library(arulesViz)

# Load data
maindata <- read.csv("maindata.csv")
data_monthly <- read.csv("data_monthly.csv")
```


```{r message=FALSE, warning=FALSE}
#data preprocessing
monthly_categorydf<-monthly_data[c("temp","humidity","precipprob","sealevelpressure","cloudcover")]
monthly_categorydf$temp_category<-cut(monthly_data$temp, breaks=c(-Inf,15,20,25,30,Inf), labels=c("Cold","Chilly","Mild","Warm","Hot"), include.lowest=TRUE)
monthly_categorydf$humidity_category<-cut(monthly_data$humidity,breaks=c(-Inf,20,30,40,50,Inf),labels=c("very low","low","moderate","high","very high"),include.lowest=TRUE)
monthly_categorydf$precipprob_category<-cut(monthly_data$precipprob,breaks=c(-Inf,15,30,45,60,Inf),labels=c("very low","low","moderate","high","very high"),include.lowest=TRUE)
monthly_categorydf$sealevelpressure_category<-cut(monthly_data$sealevelpressure,breaks=c(-Inf,1005,1010,1015,1020,Inf),labels=c("very low","low","moderate","high","very high"),include.lowest=TRUE)
monthly_categorydf$cloudcover_category<-cut(monthly_data$cloudcover ,breaks=c(-Inf,15,30,45,60,Inf),labels=c("very weak","weak","moderate","strong","very strong"),include.lowest=TRUE)

monthly_categorydf<- monthly_categorydf[, !names(monthly_categorydf) %in% c("temp","humidity","precipprob","sealevelpressure","cloudcover")]

# Convert 'monthly_categorydf' to 'transactions' format
trans_2 <- as(monthly_categorydf, "transactions")

# Use Eclat algorithm to find frequent itemsets
frequent_items_2 <- eclat(trans_2, parameter = list(supp = 0.1, maxlen = 5))

# View the frequent itemsets
inspect(frequent_items_2)

# Generate association rules
rules_2 <- apriori(trans, parameter = list(supp = 0.1, conf = 0.8))
inspect(rules_2)

# rules
rules_2

# Create a network graph of the itemsets
plot(rules_2, method = "graph", control = list(type = "items"))
```




